export const LOAD_PEOPLE_DATA = 'LOAD_PEOPLE_DATA';
export const PEOPLE_DATA_LOADING = 'PEOPLE_DATA_LOADING';
export const SET_RESULTS_PER_PAGE = 'SET_RESULTS_PER_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_PAGE_DATA = 'SET_CURRENT_PAGE_DATA';
export const SET_MAX_PAGE = 'SET_MAX_PAGE';
